version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: taskdb       # Coincide con tu application.properties
      MYSQL_ROOT_PASSWORD: root    # Coincide con tu application.properties
    ports:
      - "3307:3306"                # Puerto externo 3307
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - mysqldb

volumes:
  mysql_data: